name: Check
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scalafmt
        uses: coursier/setup-action@v1
      - name: Test Scalafmt
        run: sbt scalafmtCheck scalafmtSbtCheck Test/scalafmtCheck

  native-image:
    runs-on: macos-latest
    needs:
      - scalafmt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup sbt
        uses: coursier/setup-action@v1
      - name: Build native image
        run: sbt nativeImage
      - name: Upload native image
        if: "${{ github.ref_type == 'tag' }}"
        uses: actions/upload-artifact@v3
        with:
          name: macos-intel
          path: target/native-image/line-notify

  create-release:
    runs-on: ubuntu-latest
    needs:
      - native-image
    if: "${{ github.ref_type == 'tag' }}"
    steps:
      - name: Download native image
        uses: actions/download-artifact@v3
        with:
          name: macos-intel
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            line-notify
