name: Check
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scalafmt
        uses: coursier/setup-action@v1
      - name: Test Scalafmt
        run: sbt scalafmtCheck scalafmtSbtCheck Test/scalafmtCheck

  native-image:
    runs-on: macos-latest
    needs:
      - scalafmt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup sbt
        uses: coursier/setup-action@v1
      - name: Build native image
        run: sbt nativeImage
      - name: Archive artifacts
        if: "${{ github.ref_type == 'tag' }}"
        working-directory: target/native-image
        run: zip line-notify.zip line-notify
      - name: Upload native image
        uses: actions/upload-artifact@v3
        with:
          name: macos-intel
          path: target/native-image/line-notify.zip
      - name: Upload native image (debug)
        uses: actions/upload-artifact@v3
        with:
          name: macos-intel-debug
          path: target/native-image/line-notify

  create-release:
    runs-on: ubuntu-latest
    needs:
      - native-image
    if: "${{ github.ref_type == 'tag' }}"
    steps:
      - name: Download native image
        uses: actions/download-artifact@v3
        with:
          name: macos-intel
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            line-notify.zip

  create-formula:
    runs-on: ubuntu-latest
    needs:
      - create-release
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Download native image
        uses: actions/download-artifact@v3
        with:
          name: macos-intel
      - name: Calc SHA-256
        run: echo "sha256_macos_intel=$(sha256sum line-notify.zip | cut -f 1 -d ' ')" >> $GITHUB_ENV
      - name: Update formula
        uses: danielr1996/envsubst-action@1.1.0
        env:
          VERSION: "${{ github.ref_name }}"
          SHA256_MACOS_INTEL: "${{ env.sha256_macos_intel }}"
        with:
          input: line-notify.rb.envsubst
          output: line-notify.rb
      - name: Upload formula
        uses: actions/upload-artifact@v3
        with:
          name: formula
          path: line-notify.rb

  update-tap:
    runs-on: ubuntu-latest
    needs:
      - create-formula
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: kijuky/homebrew-tools
      - name: Download formula
        uses: actions/download-artifact@v3
        with:
          name: formula
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          delete-branch: true
